# Workflowの名前。任意に設定可能
name: EC2 auto deploy

# アクションが実行されるタイミングを設定。今回はmainブランチにpushされた時。
on:
 push:
 
#実行される処理
jobs:
  build:
    # 実行環境の指定
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_NAME }}
        username: ${{ secrets.EC2_USER_NAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd cake-php-sns-2
          git pull origin main